# Generated by Django 4.2.4 on 2023-12-05 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_story_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_active',
        ),
        migrations.AddField(
            model_name='story',
            name='viewer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='story_viewers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewers',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_view', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
