# Generated by Django 4.2.4 on 2023-12-06 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_remove_story_is_active_story_viewer_viewers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
