# Generated by Django 4.2.4 on 2023-11-28 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='https://www.shutterstock.com/image-vector/default-avatar-profile-social-media-600nw-1920331226.jpg', upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
