# Generated by Django 4.2.4 on 2023-11-29 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
