# Generated by Django 4.2.4 on 2023-12-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_story_is_active_story_viewer_viewers_user'),
        ('users', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='users_posts', to='content.post'),
            preserve_default=False,
        ),
    ]
