# Generated by Django 4.2.4 on 2023-12-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_story_is_active_story_viewer_viewers_user'),
        ('users', '0008_alter_userprofile_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='posts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_posts', to='content.post'),
        ),
    ]
