# Generated by Django 4.2.4 on 2023-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_story_is_active_story_viewer_viewers_user'),
        ('users', '0020_remove_userprofile_user_posts_userprofile_user_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_reels',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_reels', to='content.reels'),
        ),
    ]
