# Generated by Django 4.2.4 on 2023-12-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userprofile_user_highlight_userprofile_user_stories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_highlight',
            new_name='user_highlights',
        ),
    ]
